
CREATE TABLE IF NOT EXISTS AM_USAGE_UPLOADED_FILES (
   FILE_NAME varchar(255) NOT NULL,
   FILE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   FILE_PROCESSED SMALLINT DEFAULT 0,
   FILE_CONTENT BLOB(16777215) DEFAULT NULL,
   PRIMARY KEY (FILE_NAME, FILE_TIMESTAMP)
);