
CREATE TABLE AM_USAGE_UPLOADED_FILES (
   FILE_NAME varchar(255) NOT NULL,
   FILE_TIMESTAMP DATETIME2(0) DEFAULT GETDATE(),
   FILE_PROCESSED smallint DEFAULT 0,
   FILE_CONTENT VARBINARY(max) DEFAULT NULL,
   PRIMARY KEY (FILE_NAME, FILE_TIMESTAMP)
);