
CREATE TABLE AM_USAGE_UPLOADED_FILES (
   FILE_NAME varchar2(255) NOT NULL,
   FILE_TIMESTAMP TIMESTAMP(0) DEFAULT SYSTIMESTAMP,
   FILE_PROCESSED number(3) DEFAULT 0,
   FILE_CONTENT BLOB DEFAULT NULL,
   PRIMARY KEY (FILE_NAME, FILE_TIMESTAMP)
);